name: Assertions and static report
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEBSITE }}

on:
  schedule:
    - cron: '30 7 * * 1'
  workflow_dispatch:

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer 

      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site https://demo.roboto.studio --budget 75 --build-static --disable-dynamic-sampling

      - name: Deploy
        run: npx vercel deploy --cwd=.unlighthouse --prod --token ${{ secrets.VERCEL_TOKEN }}
